apps/hostel/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_view
from .views import dashboard,admin_view,warden_view,staff_view,student_view,parent_view

urlpatterns = [
    path('',dashboard.home,name='home'),
    path('admin/', include(([
        path('admin-home',admin_view.AdminHomeView.as_view(),name='admin-home'),
        path('notice-admin/',admin_view.AdminCreateNotice,name='notice-admin'),
        path('profile/<int:pk>', admin_view.AdminProfileView.as_view(), name='admin_profile'),
    ], 'dashboard'),namespace='admin_view')),

    path('warden/', include(([
        path('warden-home/',warden_view.WardenHomeView.as_view(),name='warden-home'),
        #path('signupWarden/',warden_view.WardenSignUpView,name='signupWarden'),
        path('search-warden/',warden_view.WardenSearchView,name='search-warden'),
        path('notice-warden/',warden_view.WardenCreateNotice,name='notice-warden'),
        path('request-warden/',warden_view.WardenCreateRequest,name='request-warden'),
        path('account-warden/',warden_view.WardenCreateNotice,name='account-warden'),
        path('update/<int:pk>',warden_view.WardenUpdateView.as_view(), name='update_warden'),
        path('read/<int:pk>', warden_view.WardenReadView.as_view(), name='read_warden'),
        path('delete/<int:pk>',warden_view.WardenDeleteView.as_view(), name='delete_warden'),

    ], 'dashboard'),namespace='warden_view')),

    path('staff/', include(([
        #path('signupStaff/',staff_view.StaffSignUpView,name='signupStaff'),
        path('search-staff/',staff_view.StaffSearchView,name='search-staff'),
        path('staff-home/',staff_view.StaffHomeView.as_view(),name='staff-home'),
        path('notice-staff/',staff_view.StaffCreateNotice,name='notice-staff'),
        path('staff-request/',staff_view.StaffCreateRequest,name='staff-request'),
        path('staff-account/',warden_view.WardenCreateNotice,name='staff-account'),
        path('update/<int:pk>',staff_view.StaffUpdateView.as_view(), name='update_staff'),
        path('read/<int:pk>', staff_view.StaffReadView.as_view(), name='read_staff'),
        path('delete/<int:pk>',staff_view.StaffDeleteView.as_view(), name='delete_staff'),


    ], 'dashboard'),namespace='staff_view')),

    path('student/', include(([
        path('student-home/',student_view.StudentHomeView.as_view(),name='student-home'),
        #path('signupStudent/',student_view.StudentSignUpView,name='signupStudent'),
        path('search-student/',student_view.StudentSearchView,name='search-student'),
        path('attendance/',student_view.StudentAttandanceView,name='student-attendance'),
        path('update/<int:pk>',student_view.StudentUpdateView.as_view(), name='update_student'),
        path('read/<int:pk>', student_view.StudentReadView.as_view(), name='read_student'),
        path('delete/<int:pk>',student_view.StudentDeleteView.as_view(), name='delete_student'),

    ], 'dashboard'),namespace='student_view')),

    path('parent/', include(([
        path('parent-home/',parent_view.ParentHomeView.as_view(),name='parent-home'),
        ], 'dashboard'),namespace='parent_view')),



]

vkarma/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from apps.hostel.views import dashboard,admin_view,warden_view,staff_view,student_view,parent_view
from django.conf.urls import url
from django.contrib.auth import urls
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.hostel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/admin/', admin_view.AdminSignUpView, name='admin_signup'),
    path('accounts/signup/warden/', warden_view.WardenSignUpView, name='warden_signup'),
    path('accounts/signup/staff/', staff_view.StaffSignUpView, name='staff_signup'),
    path('accounts/signup/student/',student_view.StudentSignUpView, name='student_signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/staff_view/create_notice.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Admin | Notice {%endblock%}
{% block heading %} Notice  {% endblock %}
{% block menu %}profile {% endblock %}
{% block style %}
.card {
  margin-bottom:20px ;
  border-radius:10px ;
  opacity:0.8;
  padding:100px
  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  transition: all 0.3s cubic-bezier(.25,.8,.25,1);

}
.card:hover{
  box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
}
ion-icon {
    color:#fd9426;
    font-size:33px;
    float:right;
    margin:0 3px;
    padding:3px;
    line-height:20px;
    display:block;
    border: 0px solid #fd9426;
    border-radius:10px;
    cursor:pointer;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);

  }
  ion-icon:hover{
    transition:0.1s;
    background:#fd9426;
    color:#FFF;
    border: 1px solid #fd9426;
    box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
  }
 .menu {
  top: -71px;
  position: relative;
 }
 .box{
   margin-bottom:20px ;
   margin-left: ;
   border-radius:10px ;
   box-shadow:0 0 0 0.4;
   opacity:0.8;
   width: 100%;
   cursor:pointer;
   height: 310px;
   border: 1px solid #ced4da;
 }
 .box:hover{
   border: 1px solid rgb(255,128,33);
   background:.rgb(255,128,33);
   transition:0.4s;
  }
  .span2 {
    font-size: 16px;
    color: #999999;
    font-weight:bolder;
    text-align: center;
    padding-left: 15px;
  }
  .main h4 {
   color:#000;
   background: #ced4da;
   border-radius:10px;
   padding:0px 10px;
 }
 .box img {
  width:200px;
  height:200px;
  padding:10px;
  border-radius:50%;
 }
 .box a {
   background:rgb(255,128,33);
   color:#ffffff;
   font-size:20px;
   padding:5px 20px;
   border-radius:20px;
   margin-left:20px;
   letter-spacing:1px;
 }
 .form-control {
    height: 150px !important;
    background: #fff !important;
    color: #000000 !important;
    font-size: 18px;
    border-radius: 10px;
    -webkit-box-shadow: none !important;
    box-shadow:none;
  }
  input,select, optgroup {
      margin: 10px;
      width: 100%;
      font-family: inherit;
      font-size: inherit;
      line-height: inherit;
      outline: none;
      border: 1px solid #999999;
      color:rgb(255,128,33);
      border-radius: 10px;
      height: 52px !important;
      font-size: 18px;
      background: #fff !important;
      color: #000000 !important;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);

  }
  input:hover,select:hover, optgroup:hover
  , textarea:hover {
       transition:0.4s;
       border: 1px solid rgb(255,128,33);
  }
  textarea {
    margin: 10px;
    width: 100%;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    outline: none;
    border: 1px solid #999999;
    color:rgb(255,128,33);
    border-radius: 10px;
    height: 152px !important;
    font-size: 18px;
    background: #fff !important;
    color: #000000 !important;
        box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        transition: all 0.3s cubic-bezier(.25,.8,.25,1);

  }
  .main h4 {
    color:rgb(255,128,33);
    background: #ffffff;
    border-radius:10px;
    padding:0px 10px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  }
  button {
    outline:none;
    border:none;
    font-size:20px;
    padding:2px 10px;
    background:rgb(255,128,33);
    color:#ffffff;

    cursor:pointer;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);

  }
            .ripple {
              background-position: center;
              transition: background 0.8s;
            }
            .ripple:hover {
              background: #fc6e05 radial-gradient(circle, transparent 1%, #db8646  1%) center/15000%;
            }
            .ripple:active {
              background-color: rgb(255,128,33);
              background-size: 100%;
              transition: background 0s;
            }

            /* Button style */


{% endblock %}
{% block nav-link %}
         <li  ><a style="font-size:18px;" href="{% url 'staff_view:staff-home' %}"> Home</a></li>
         <hr>
         <li><a style="font-size:18px;" href="{% url 'student_signup' %}">Add Student</a><li>
         <hr>
         <li><a style="font-size:18px;" href="{% url 'staff_view:staff-request' %}"> Send Request</a></li>
      
         <hr>
         <li class="colorlib-active"  ><a style="font-size:18px;" href="{% url 'staff_view:notice-staff' %}"> Send Notice</a></li>

         <hr>
         <li><a style="font-size:18px;" href="{% url 'student_view:search-student' %}"> Search Student</a></li>

         <hr>
         <li ><a style="color:#fd9426;" id='logout' href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> logout</a></li>
{% endblock %}
{% block profile%}
<a Class="" href="#"><ion-icon name="contact"></ion-icon></a>
<a Class="" href="#"><ion-icon name="notifications"></ion-icon></a>
<a Class="" href="#"><ion-icon name="mail"></ion-icon></a>
<h2 style="" class="h4 font-weight-bold d">

{% endblock %}

    {% block body %}
    <div class="main">
      <h4 style="margin-top:20px;margin-bottom:30px">Fill Information</h4>
<div class="card">


    <form method="post" novalidate enctype="multipart/form-data">
{% csrf_token %}

<div  class="form-row">
  <div class="form-group col-md-6 mb-0">
             {{ form.Subject|as_crispy_field }}
  </div>
  <div class="form-group col-md-5 mb-0">
             {{ form.users|as_crispy_field }}
  </div>

</div>
<div  class="form-row">
    <div class=" des form-group col-md-11 mb-0">
               {{ form.description|as_crispy_field }}
    </div>

</div>

<button type="submit" style="border-radius:10px; margin:10px;" class="ripple">Submit</button>
</div>
</form>
</div>
{% endblock %}

templates/staff_view/delete_student.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div style="background:#fc3d39;" class="modal-header d-flex justify-content-center">
    <h3 style="color:#fff"; class="modal-title">Are you sure ?</h3>
    <!--button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button-->
  </div>

  <div class="modal-body">
  <p style="color:#fc3d39; text-align:center; font-size:30px;" > <i class="fa fa-times fa-4x animated rotateIn"></i></p>
  </div>

  <div class="modal-footer flex-center">
    <a data-dismiss="modal" style=" cursor:pointer; border-radius:10px;color:#fc3d39; background:none; border:none;"">Cancel</a>
    <button style="border-radius:10px; background:#fc3d39; border:none;"; type="submit" class="delete-btn btn btn-danger waves-effect">Delete</button>
  </div>

</form>

templates/staff_view/read_student.html
{% load widget_tweaks %}

<div style="background:#53d769;"  class="modal-header d-flex justify-content-center">
  <h3 style="color:#fff"; class="modal-title">Student Details</h3>
  </div>

<div class="modal-body">

  <div class="">
    Name :
    <br>
  <strong  style="font-size:18px;"> {{field.firstName}} {{field.lastName}}</strong>
  </div>
  <div class="">
    Hostel Name :
    <br>
     <strong  style="font-size:18px;"> {{field.hostel_name}}</strong>
  </div>
  <div class="">
    Phone :
    <br>
    <strong  style="font-size:18px;"> {{field.phone_number}}</strong>

  </div>
  <div class="">
    Email :
    <br>
    <strong  style="font-size:18px;"> {{field.email}}</strong>
  </div>
  <div class="">
    Parent :
    <br>
    <strong  style="font-size:18px;"> {{field.parent_name}}</strong>
  </div>
  <div class="">
    Class Name :
    <br>
    <strong  style="font-size:18px;"> {{field.class_name}}</strong>
  </div>
  <div class="">
    Roll Number :
    <br>
    <strong  style="font-size:18px;"> {{field.roll_number}}</strong>
  </div>


</div>

<div class="modal-footer">
    <button style="border-radius:10px; background:#53d769;; border:none; color:#fff;"; type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

templates/staff_view/search_student.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Student | Search {%endblock%}
{% block heading %} Search   {% endblock %}
{% block menu %}Search {% endblock %}

{% block style %}
ion-icon {
    color:#fd9426;
    font-size:33px;
    float:right;
    margin:0 3px;
    padding:3px;
    line-height:20px;
    display:block;
    border: 0px solid #fd9426;
    border-radius:10px;
    cursor:pointer;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);

  }
  ion-icon:hover{
    transition:0.1s;
    background:#fd9426;
    color:#FFF;
    border: 1px solid #fd9426;
    box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
  }
  .menu {
    top: -71px;
    position: relative;
  }
  .box
  {
    margin-bottom:20px ;
    border-radius:10px ;
    opacity:0.8;
    width: 100%;
    height: 330px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);
  }
  .box:hover{
    background:.rgb(255,128,33);
    box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);

  }



  .span2
  {
    font-size: 16px;
    color: #999999;
    font-weight:bolder;
    text-align: center;
    margin-bottom:0px;

  }
  #span3{
    color:black;
  }

  h4 {
    color:rgb(255,128,33);
    background: #ffffff;
      border-radius:10px;
    padding:0px 10px;
    width:100%;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  }

  .box img {
    width:100%;
    height:220px;
    padding:10px;
    border-radius:50%;

  }
  .box .a1 ion-icon {
    color:#fc3d39

  }
  .box .a1 ion-icon:hover {
    background:#fc3d39;
    color:#fff;
    border:1px solid #fc3d39;
  }
  .box .a3 ion-icon {
    color:#53d769;
  }
  .box .a3 ion-icon:hover {
    background:#53d769;
    color:#fff;
    border:1px solid #53d769;
  }
        input,select, optgroup, textarea {
          margin: 10px;
          width: 100%;
          font-family: inherit;
          font-size: inherit;
          line-height: inherit;
          outline: none;
          border:none;
          color:rgb(255,128,33);
          border-radius: 10px;
          height: 52px !important;
          font-size: 18px;
          background: #fff !important;
          color: #000000 !important;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);

        }
        input:hover,select:hover, optgroup:hover
        , textarea:hover {
          border: 1px solid #999999;
        }
        button {
          outline:none;
          border:none;
          font-size:20px;
          padding:2px 10px;
          background:rgb(255,128,33);
          color:#ffffff;

          cursor:pointer;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);

        }
                  .ripple {
                    background-position: center;
                    transition: background 0.8s;
                  }
                  .ripple:hover {
                    background: #fc6e05 radial-gradient(circle, transparent 1%, #db8646  1%) center/15000%;
                  }
                  .ripple:active {
                    background-color: rgb(255,128,33);
                    background-size: 100%;
                    transition: background 0s;
                  }

                  /* Button style */



{% endblock %}
{% block profile%}
<a Class="" href="#"><ion-icon name="contact"></ion-icon></a>
<a Class="" href="#"><ion-icon name="notifications"></ion-icon></a>
<a Class="" href="#"><ion-icon name="mail"></ion-icon></a>
<h2 style="" class="h4 font-weight-bold d">

{% endblock %}
{% block nav-link %}
         <li  ><a style="font-size:18px;" href="{% url 'staff_view:staff-home' %}"> Home</a></li>
         <hr>
         <li  ><a style="font-size:18px;" href="{% url 'student_signup' %}">Add Student</a><li>
          <hr>
         <li><a style="font-size:18px;" href="{% url 'staff_view:staff-request' %}"> Send Request</a></li>
         <hr>
         <li ><a style="font-size:18px;" href="{% url 'staff_view:notice-staff' %}"> Send Notice</a></li>
      <hr>
         <li class="colorlib-active"><a style="font-size:18px;" href="{% url 'student_view:search-student' %}"> Search Student</a></li>
         
         <hr>
         <li ><a style="color:#fd9426;" id='logout' href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> logout</a></li>
{% endblock %}

{% block body %}
{% include "_modal.html" %}
  <div class="col-md-12">
      <form  method="post">
         <div  class="form-row">
           <div class="form-group col-md-12 mb-0">
                      {%csrf_token%}
                    {{ form |crispy}}
           </div>
         </div>
        <button style="margin-top:;border-radius:10px" type="submit"  class="ripple">
             Search
       </button>
     </form>
  <div class="main">
    <br>
    <div class="container">
      <div class="row">
        {% if data %}
        <h4 style="margin-bottom:20px">Total Result : {{ data.count }}</h4>
         <br>

        {% for field in data %}


            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-3 ">
              <div class="box">
                <img src="{% static 'images/logo-2.png' %}" alt="img" class="">

                     <p class="span2">{{field.firstName}} {{field.lastName}}</p>

                        <p class="span2">{{field.hostel_name}}</p>

                        <a class="delete-warden a1" data-id="{% url 'student_view:delete_student' field.pk %}">
                          <ion-icon name="trash">
                        </a>
                        <a class="update-warden a2" data-id="{% url 'student_view:update_student' field.pk %}" >
                          <ion-icon name="create" >
                        </a>
                        <a class="read-warden a3" data-id="{% url 'student_view:read_student' field.pk %}">
                          <ion-icon name="eye">
                        </a>
                                            </div>
          </div>
{% endfor %}


        {% endif %}


      </div>
    </div>
  </div>
{% endblock %}
{% block extrascripts %}
  <script type="text/javascript">
    $(function () {

      // Update book buttons
      $(".update-warden").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Read book buttons
      $(".read-warden").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Delete book buttons
      $(".delete-warden").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      })

      // Hide message
      $(".alert").fadeTo(2000, 700).slideUp(700, function(){
        $(".alert").slideUp(700);
      });

    });
  </script>
{% endblock extrascripts %}

templates/staff_view/staff_home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Staff | Home {%endblock%}
{% block heading %} <h3>Welcome</h3>  {% endblock %}
{% block menu %}profile {% endblock %}
{% block style %}
      ion-icon {
          color:#fd9426;
          font-size:33px;
          float:right;
          margin:0 3px;
          padding:3px;
          line-height:20px;
          display:block;
          border: 0px solid #fd9426;
          border-radius:10px;
          cursor:pointer;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);

        }
        ion-icon:hover{
          transition:0.1s;
          background:#fd9426;
          color:#FFF;
          border: 1px solid #fd9426;
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
        }
        .menu {
          top: -71px;
          position: relative;
        }
        .box
        {
          margin-bottom:20px ;
          border-radius:10px ;
          opacity:0.8;
          width: 100%;
          height: 330px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);
        }
        .box:hover{
          background:.rgb(255,128,33);
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);

        }
        .modal-box {
          background:red;
        }

        .box1
        {
          margin:30px ;
          border-radius:10px ;
          opacity:0.8;
          width: 100%;
          height: 330px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);
        }
        .box1:hover{
          background:.rgb(255,128,33);
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);

        }



        .span2
        {
          font-size: 16px;
          color: #999999;
          font-weight:bolder;
          text-align: center;
          margin-bottom:0px;

        }
        #span3{
          color:black;
        }
        .main h4 {
          color:rgb(255,128,33);
          background: #ffffff;
          border-radius:10px;
          padding:0px 10px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        }
        .box img {
          width:100%;
          height:220px;
          padding:10px;
          border-radius:50%;

        }
        .box .a1 ion-icon {
          color:#fc3d39

        }
        .box .a1 ion-icon:hover {
          background:#fc3d39;
          color:#fff;
          border:1px solid #fc3d39;
        }
        .box .a3 ion-icon {
          color:#53d769;
        }
        .box .a3 ion-icon:hover {
          background:#53d769;
          color:#fff;
          border:1px solid #53d769;
        }
        .btn.btn-primary {
    background: #f05d23;
    border: 1px solid #f05d23;
    color: #fff;
    position: relative;
    left: 40%;
    margin-top: 10%;
    /* top: 120%; */
}
.box1 p {
  text-align:center;
  font-size:18px;
  color:#999999;
   margin-bottom:-1rem;

}


{% endblock %}
 {% block nav-link %}
          <li class="colorlib-active" ><a style="font-size:18px;" href="{% url 'staff_view:staff-home' %}"> Home</a></li>
          <hr>
          <li ><a style="font-size:18px;" href="{% url 'student_signup' %}">Add Student</a><li>
          <hr>
          <li><a style="font-size:18px;" href="{% url 'staff_view:staff-request' %}"> Send Request</a></li>
          <hr>
          <li ><a style="font-size:18px;" href="{% url 'staff_view:notice-staff' %}"> Send Notice</a></li>
          <hr>
          <li><a style="font-size:18px;" href="{% url 'student_view:search-student' %}"> Search Student</a></li>
          <hr>
          <li><a style="font-size:18px;" href="{% url 'student_view:search-student' %}"> Attendance</a></li>
          <hr>
          
          <li ><a style="color:#fd9426;" id='logout' href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> logout</a></li>
 {% endblock %}

{% block body %}
{% include "_modal.html" %}
<div class="main">
   <h4 style="margin-top:">Dashboard</h4>
     <div class="container-fluid  ">
       <div class="row">
            <div id='allwarden' style="height:100px;cursor:pointer;" class="box1 col-md-3">
              <p >Total Student</p>
              <p style="font-size:40px;" >{{ data.count }}</p>
              </div>
              <div  style="height:100px; cursor:pointer;" class="box1 col-md-3">
                <p>Recent Added </p>
                {% if data %}
                <p style="font-size:20px;margin-top:1rem;" >{{ data.last.firstName }} {{ data.last.lastName }}</p>
                {% else %}
                <p style="font-size:20px;margin-top:1rem;" >---</p>
                {% endif %}
                </div>
                <div style="height:100px;cursor:pointer;" class="box1 col-md-3">
                  <p >Recent Deleted</p>
                  <p style="font-size:20px; margin-top:1rem;" > - - - </p>
                  </div>

       </div>
  </div>
</div>

<div class="main">
     <h4>All Student</h4>
  <div class="row">
    {% if data %}
       {% for field in data %}
         <div class="col-xs-1 col-sm-1 col-md-1 col-lg-3 ">
           <div class="box">
             <img src="{% static 'images/logo-2.png' %}" alt="img" class="">

                  <p class="span2">{{field.firstName}} {{field.lastName}}</p>

                     <p class="span2">{{field.hostel_name}}</p>

                     <a class="delete-warden a1" data-id="{% url 'student_view:delete_student' field.pk %}">
                       <ion-icon name="trash">
                     </a>
                     <a class="update-warden a2" data-id="{% url 'student_view:update_student' field.pk %}" >
                       <ion-icon name="create" >
                     </a>
                     <a class="read-warden a3" data-id="{% url 'student_view:read_student' field.pk %}">
                       <ion-icon name="eye">
                     </a>
                   </div>
       </div>
       {% endfor %}
       {% else %}

             <a style="border-radius:10px;" type="submit" class="btn btn-primary" href="{% url 'student_signup' %}">
                 Add new Student
             </a>
     {% endif %}
  </div>
</div>
{% endblock %}
{% block profile%}
<a Class="admin-profile" data-id="{ url  'admin_view:admin_profile }"><ion-icon name="contact"></ion-icon></a>

<a Class="" href="#"><ion-icon name="notifications"></ion-icon></a>
<a Class="" href="#"><ion-icon name="mail"></ion-icon></a>
<h2 style="" class="h4 font-weight-bold d">

{% endblock %}

{% block extrascripts %}
  <script type="text/javascript">
    $(function () {

      // Update book buttons
      $(".update-warden").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Read book buttons
      $(".read-warden").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Delete book buttons
      $(".delete-warden").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      })

      // Hide message
      $(".alert").fadeTo(2000, 700).slideUp(700, function(){
        $(".alert").slideUp(700);
      });

    });
  </script>
{% endblock extrascripts %}