apps/hostel/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_view
from .views import dashboard,admin_view,warden_view,staff_view,student_view,parent_view

urlpatterns = [
    path('',dashboard.home,name='home'),
    path('admin/', include(([
        path('admin-home',admin_view.AdminHomeView.as_view(),name='admin-home'),
        path('notice-admin/',admin_view.AdminCreateNotice,name='notice-admin'),
        path('profile/<int:pk>', admin_view.AdminProfileView.as_view(), name='admin_profile'),
    ], 'dashboard'),namespace='admin_view')),

    path('warden/', include(([
        path('warden-home/',warden_view.WardenHomeView.as_view(),name='warden-home'),
        #path('signupWarden/',warden_view.WardenSignUpView,name='signupWarden'),
        path('search-warden/',warden_view.WardenSearchView,name='search-warden'),
        path('notice-warden/',warden_view.WardenCreateNotice,name='notice-warden'),
        path('request-warden/',warden_view.WardenCreateRequest,name='request-warden'),
        path('account-warden/',warden_view.WardenCreateNotice,name='account-warden'),
        path('update/<int:pk>',warden_view.WardenUpdateView.as_view(), name='update_warden'),
        path('read/<int:pk>', warden_view.WardenReadView.as_view(), name='read_warden'),
        path('delete/<int:pk>',warden_view.WardenDeleteView.as_view(), name='delete_warden'),

    ], 'dashboard'),namespace='warden_view')),

    path('staff/', include(([
        #path('signupStaff/',staff_view.StaffSignUpView,name='signupStaff'),
        path('search-staff/',staff_view.StaffSearchView,name='search-staff'),
        path('staff-home/',staff_view.StaffHomeView.as_view(),name='staff-home'),
        path('notice-staff/',staff_view.StaffCreateNotice,name='notice-staff'),
        path('staff-request/',staff_view.StaffCreateRequest,name='staff-request'),
        path('staff-account/',warden_view.WardenCreateNotice,name='staff-account'),
        path('update/<int:pk>',staff_view.StaffUpdateView.as_view(), name='update_staff'),
        path('read/<int:pk>', staff_view.StaffReadView.as_view(), name='read_staff'),
        path('delete/<int:pk>',staff_view.StaffDeleteView.as_view(), name='delete_staff'),


    ], 'dashboard'),namespace='staff_view')),

    path('student/', include(([
        path('student-home/',student_view.StudentHomeView.as_view(),name='student-home'),
        #path('signupStudent/',student_view.StudentSignUpView,name='signupStudent'),
        path('search-student/',student_view.StudentSearchView,name='search-student'),
        path('attendance/',student_view.StudentAttandanceView,name='student-attendance'),
        path('update/<int:pk>',student_view.StudentUpdateView.as_view(), name='update_student'),
        path('read/<int:pk>', student_view.StudentReadView.as_view(), name='read_student'),
        path('delete/<int:pk>',student_view.StudentDeleteView.as_view(), name='delete_student'),

    ], 'dashboard'),namespace='student_view')),

    path('parent/', include(([
        path('parent-home/',parent_view.ParentHomeView.as_view(),name='parent-home'),
        ], 'dashboard'),namespace='parent_view')),



]

vkarma/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from apps.hostel.views import dashboard,admin_view,warden_view,staff_view,student_view,parent_view
from django.conf.urls import url
from django.contrib.auth import urls
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.hostel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/admin/', admin_view.AdminSignUpView, name='admin_signup'),
    path('accounts/signup/warden/', warden_view.WardenSignUpView, name='warden_signup'),
    path('accounts/signup/staff/', staff_view.StaffSignUpView, name='staff_signup'),
    path('accounts/signup/student/',student_view.StudentSignUpView, name='student_signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/student_view/attendance.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Student | Dashboard {%endblock%}
{% block heading %}<h3>Welcome</h3>  {% endblock %}
{{% block style %}
      ion-icon {
          color:#fd9426;
          font-size:33px;
          float:right;
          margin:0 3px;
          padding:3px;
          line-height:20px;
          display:block;
          border: 0px solid #fd9426;
          border-radius:10px;
          cursor:pointer;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);

        }
        ion-icon:hover{
          transition:0.1s;
          background:#fd9426;
          color:#FFF;
          border: 1px solid #fd9426;
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
        }
        .menu {
          top: -71px;
          position: relative;
        }
        .box
        {
          margin-bottom:20px ;
          border-radius:10px ;
          opacity:0.8;
          width: 100%;
          height: 330px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);
        }
        .box:hover{
          background:.rgb(255,128,33);
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);

        }
        .modal-box {
          background:red;
        }

        .box1
        {
          margin:30px ;
          border-radius:10px ;
          opacity:0.8;
          width: 100%;
          height: 330px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
          transition: all 0.3s cubic-bezier(.25,.8,.25,1);
        }
        .box1:hover{
          background:.rgb(255,128,33);
          box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);

        }



        .span2
        {
          font-size: 16px;
          color: #999999;
          font-weight:bolder;
          text-align: center;
          margin-bottom:0px;

        }
        #span3{
          color:black;
        }
        .main h4 {
          color:rgb(255,128,33);
          background: #ffffff;
          border-radius:10px;
          padding:0px 10px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        }
        .box img {
          width:100%;
          height:220px;
          padding:10px;
          border-radius:50%;

        }
        .box .a1 ion-icon {
          color:#fc3d39

        }
        .box .a1 ion-icon:hover {
          background:#fc3d39;
          color:#fff;
          border:1px solid #fc3d39;
        }
        .box .a3 ion-icon {
          color:#53d769;
        }
        .box .a3 ion-icon:hover {
          background:#53d769;
          color:#fff;
          border:1px solid #53d769;
        }
        .btn.btn-primary {
    background: #f05d23;
    border: 1px solid #f05d23;
    color: #fff;
    position: relative;
    left: 40%;
    margin-top: 10%;
    /* top: 120%; */
}
.box1 p {
  text-align:center;
  font-size:18px;
  color:#999999;
   margin-bottom:-1rem;

}


{% endblock %}
{% block profile%}
<a Class="" href="#"><ion-icon name="contact"></ion-icon></a>
<a Class="" href="#"><ion-icon name="notifications"></ion-icon></a>
<a Class="" href="#"><ion-icon name="mail"></ion-icon></a>
<h2 style="" class="h4 font-weight-bold d">

{% endblock %}

{% block nav-link %}
          <li  ><a style="font-size:18px;" href="{% url 'student_view:student-home' %}"> Home</a></li>
          <hr>
          <li class="colorlib-active"><a style="font-size:18px;" href="{% url 'student_view:student-attendance' %}">My Attendance</a><li>
          <hr>
          <li ><a style="font-size:18px;" href="{% url 'admin_view:notice-admin' %}"> Send Request</a></li>
          <hr>
          <li><a style="font-size:18px;" href="{% url 'warden_view:search-warden' %}"> Complaint</a></li>
        
          <hr>
          <li ><a style="color:#fd9426;" id='logout' href="/logout"><i class="fa fa-sign-out"></i> logout</a></li>
 {% endblock %}

templates/student_view/student_home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Student | Dashboard {%endblock%}
{% block heading %} Welcome  {% endblock %}
{% block style %}
      ion-icon {
          color:#fd9426;
          font-size:30px;
          float:right;
          margin:0 3px;
          padding:3px;
          line-height:20px;
          display:block;
          border: 1px solid #fd9426;
          border-radius:10px;
          cursor:pointer;
          transition:0.1s;
        }
        ion-icon:hover{
          transition:0.1s;
          background:#fd9426;
          color:#FFF;
          border: 1px solid #fd9426;
        }
        .menu {
          top: -71px;
          position: relative;
        }
        .box
        {
          margin-bottom:20px ;
          border-radius:10px ;
          box-shadow:0 0 0 0.4;
          opacity:0.8;
          width: 100%;
          height: 330px;
          border: 2px solid #ced4da;
        }
        .box:hover{

          border: 1px solid rgb(255,128,33);
          background:.rgb(255,128,33);

        }



        .span2
        {
          font-size: 16px;
          color: #999999;
          font-weight:bolder;
          text-align: center;
          margin-bottom:0px;

        }
        #span3{
          color:black;
        }
        .main h4 {
          color:#000;
          background: #ced4da;
          border-radius:10px;
          padding:0px 10px;
        }
        .box img {
          width:100%;
          height:220px;
          padding:10px;
          border-radius:50%;

        }
        .box .a1 ion-icon {
          color:#fc3d39

        }
        .box .a1 ion-icon:hover {
          background:#fc3d39;
          color:#fff;
          border:1px solid #fc3d39;
        }
        .box .a3 ion-icon {
          color:#53d769;
        }
        .box .a3 ion-icon:hover {
          background:#53d769;
          color:#fff;
          border:1px solid #53d769;
        }
        .btn.btn-primary {
    background: #f05d23;
    border: 1px solid #f05d23;
    color: #fff;
    position: relative;
    left: 40%;
    margin-top: 10%;
    /* top: 120%; */
}

{% endblock %}
 {% block nav-link %}
          <li class="colorlib-active" ><a style="font-size:18px;" href="{% url 'admin_view:admin-home' %}"> Home</a></li>
          <li ><a style="font-size:18px;" href="{% url 'warden_view:signupWarden' %}">My Attendance</a><li>
          <li ><a style="font-size:18px;" href="{% url 'admin_view:notice-admin' %}"> Send Request</a></li>
          <li><a style="font-size:18px;" href="{% url 'warden_view:search-warden' %}"> Search Warden</a></li>
          <br>
          <hr>
          <li ><a style="color:#fd9426;" id='logout' href="/logout"><i class="fa fa-sign-out"></i> logout</a></li>
 {% endblock %}

{% block body %}
   {% include "_modal.html" %}
<div class="main">
   <h4 style="margin-top:20px">Dashboard</h4>
   <div class="">
       <h2 style="text-align:center;">No Data</h2>

   </div>
</div>
<div class="main">
                                   <h4>My Feed</h4>
  <div class="container">
    <div class="row">

    </div>
  </div>
</div>
{% endblock %}